### ISSUE TITLE
Do competitions have to be in Russia necessarily?

### ISSUE THREAD

**Issue by adslots** [suphair/funcubing.org#2]
Hi! I am a greek cuber and i wanna do a competition only for me and my friends in Greece? is there a chance that i could possibly do that or do competitions have to be only in Russia?

**Comment by suphair** [comment]
Hello. Competitions can be held anywhere, even virtually.
But they will not get into the "Russian Speedcubing Federation Rankings".

If you have any questions or suggestions, please contact me.

**Comment by adslots** [comment]
Okay thank you so much! How do i upload the scores?

**Comment by adslots** [comment]
I have sent you an email for a question, is that how im supposed to contact you?
